channels:
  - conda-forge
  - nesii/label/dev-esmf
dependencies:
  - python=3.5
  - esmpy
  - xarray
  - numpy
  - scipy
  - sphinx
  - jupyter
  - pip:
    - nbsphinx
    - sphinx_rtd_theme
    - numpydoc
